[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-10_x"]

[phases.install]
cmds = ["cd frontend && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[variables]
NIXPACKS_NODEJS_VERSION = "18"
